-- Drop database cũ nếu tồn tại
DROP DATABASE QUANLYNHAHANG;
GO

-- Tạo Database
CREATE DATABASE QUANLYNHAHANG;
GO

-- Sử dụng database Quản lý nhà hàng
USE QUANLYNHAHANG
GO
---------------------------------------------------------------------------------------------------
------------------------------ CÀI ĐẶT CƠ SỞ DỮ LIỆU ----------------------------------------------
-- BẢNG 1 --
CREATE TABLE BANAN (
	MABANAN INT PRIMARY KEY,
	SOGHE INT ,
	TRANGTHAI NVARCHAR(10) CHECK (TRANGTHAI IN (N'Trống', N'Đã đặt')) DEFAULT (N'Trống'),
);
GO


-- BẢNG 2 --
CREATE TABLE LOAIMONAN (
	MALOAIMONAN INT PRIMARY KEY,
	TENGOI NVARCHAR(50),
);
GO

-- BẢNG 3 --
CREATE TABLE MONAN (
	MAMONAN INT PRIMARY KEY,
	TENGOI NVARCHAR(50),
	DONVITINH NVARCHAR(20),
	DONGIA INT,
	MALOAIMONAN INT REFERENCES LOAIMONAN(MALOAIMONAN)
);
GO

-- BẢNG 4 --
CREATE TABLE NHASANXUAT (
	MANHASANXUAT INT PRIMARY KEY,
	TENNHASANXUAT NVARCHAR(50) NOT NULL,
	DIADIEM NVARCHAR(50) NOT NULL

);
GO

-- BẢNG 5 --
CREATE TABLE NGUYENLIEU(
	MANGUYENLIEU INT PRIMARY KEY,
	TENNGUYENLIEU NVARCHAR(50) NOT NULL,
	DONVITINH NVARCHAR(20),
	MANHASANXUAT INT REFERENCES NHASANXUAT(MANHASANXUAT)
);
GO

-- BẢNG 6 --
CREATE TABLE BOPHAN (
	MABOPHAN INT PRIMARY KEY,
	TEBOPHAN NVARCHAR(50),
	MAQUANLY INT
);
GO

-- BẢNG 7 --
CREATE TABLE NHANVIEN (
	MANHANVIEN INT PRIMARY KEY,
	HOVATEN NVARCHAR(50),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(3) CHECK (GIOITINH IN(N'Nam', N'Nữ')) DEFAULT N'Nữ',
	DIACHI NVARCHAR(50),
	SODIENTHOAI CHAR(15),
	LUONG INT,
	MABOPHAN INT REFERENCES BOPHAN(MABOPHAN)
	
);
GO

-- BẢNG 8 --
CREATE TABLE PHIEUNHAP (
	MAPHIEUNHAP INT PRIMARY KEY,
	NGAYNHAP DATE,
	THANHTIEN INT,
	MANHANVIEN INT REFERENCES NHANVIEN(MANHANVIEN)
);
GO

-- BẢNG 9 --
CREATE TABLE CHITIETPHIEUNHAP (
	MAPHIEUNHAP INT REFERENCES PHIEUNHAP(MAPHIEUNHAP),
	MANGUYENLIEU INT REFERENCES NGUYENLIEU(MANGUYENLIEU),
	SOLUONG INT,
	DONGIA INT,
	PRIMARY KEY(MAPHIEUNHAP, MANGUYENLIEU)
);
GO

-- BẢNG 10 --
CREATE TABLE KHACHHANG (
	MAKHACHHANG INT PRIMARY KEY,
	HOTEN NVARCHAR(50),
	SODIENTHOAI CHAR(15),
	DIACHI NVARCHAR(50),
);
GO

-- BẢNG 11 --
CREATE TABLE PHIEUYEUCAU (
	MAPHIEUYEUCAU INT PRIMARY KEY,
	TENPHIEU NVARCHAR (50),
	NGAYVIETPHIEU DATE,
	MAKHACHHANG INT REFERENCES KHACHHANG(MAKHACHHANG)
);
GO

-- BẢNG 12 --
CREATE TABLE HOADON (
	MAHOADON INT PRIMARY KEY,
	NGAYLAPHOADON DATE,
	THANHTIEN INT,
	MAPHIEUYEUCAU INT REFERENCES PHIEUYEUCAU(MAPHIEUYEUCAU),
	MANHANVIEN INT REFERENCES NHANVIEN(MANHANVIEN)
	
);
GO

-- BẢNG 13 --
CREATE TABLE CHITIETBANAN (
	MABANAN INT REFERENCES BANAN(MABANAN),
	MAHOADON INT REFERENCES HOADON(MAHOADON),
	THOIGIANDAT DATE,
);
GO

-- BẢNG 14 --
CREATE TABLE CHITIETPHIEUYEUCAU(
	MAMONAN INT REFERENCES MONAN(MAMONAN),
	MAPHIEUYEUCAU INT REFERENCES PHIEUYEUCAU(MAPHIEUYEUCAU),
	DONGIA INT,
	DONVITINH NVARCHAR(20),
	SOLUONG INT
); 
GO
----------------------------------------------------------------------------------------
------------------------TẠO THỦ TỤC THÊM DỮ LIỆU----------------------------------------
-- BẢNG 1 -- Bàn ăn
CREATE PROCEDURE SP_BANAN_INSERT
	@MABANAN INT,
	@SOGHE INT,
	@TRANGTHAI NVARCHAR(10)
AS
BEGIN
	INSERT INTO BANAN(MABANAN, SOGHE, TRANGTHAI)
	VALUES(@MABANAN, @SOGHE, @TRANGTHAI)

END
GO
-- Xóa dữ liệu cũ trong bảng
DELETE BANAN;
GO
-- Thêm dữ liệu


[dbo].[SP_BANAN_INSERT] 1, 10, N'Trống'
GO
[dbo].[SP_BANAN_INSERT] 2, 10, N'Trống'
GO
[dbo].[SP_BANAN_INSERT] 3, 10, N'Trống';
GO
[dbo].[SP_BANAN_INSERT] 4, 10, N'Trống';
GO
[dbo].[SP_BANAN_INSERT] 5, 10, N'Trống';
GO
[dbo].[SP_BANAN_INSERT] 6, 10, N'Trống';
GO
[dbo].[SP_BANAN_INSERT] 7, 10, N'Trống';
GO
[dbo].[SP_BANAN_INSERT] 8, 10, N'Trống';
GO
[dbo].[SP_BANAN_INSERT] 9, 10, N'Trống';
GO
[dbo].[SP_BANAN_INSERT] 10, 15, N'Trống';
GO
[dbo].[SP_BANAN_INSERT] 11, 15, N'Trống';
GO
[dbo].[SP_BANAN_INSERT] 12, 15, N'Trống';
GO
[dbo].[SP_BANAN_INSERT] 13, 15, N'Trống';
GO
[dbo].[SP_BANAN_INSERT] 14, 15, N'Trống';
GO
[dbo].[SP_BANAN_INSERT] 15, 15, N'Trống';
GO
[dbo].[SP_BANAN_INSERT] 16, 15, N'Trống';
GO
[dbo].[SP_BANAN_INSERT] 17, 15, N'Trống';
GO
[dbo].[SP_BANAN_INSERT] 18, 15, N'Trống';
GO
[dbo].[SP_BANAN_INSERT] 19, 15, N'Trống';
GO
[dbo].[SP_BANAN_INSERT] 20, 15, N'Trống';
GO

-- BẢNG 2 -- Loại món ăn
CREATE PROCEDURE SP_LOAIMONAN_INSERT
	@MALOAIMONAN INT,
	@TENGOI NVARCHAR(20)
AS
BEGIN
	INSERT INTO LOAIMONAN(MALOAIMONAN, TENGOI)
	VALUES(@MALOAIMONAN, @TENGOI)
END
GO
-- Xóa dữ liệu cũ
DELETE LOAIMONAN;
GO
-- Thêm dữ liệu mới
[dbo].[SP_LOAIMONAN_INSERT] 1, N'Món Gà'
GO
[dbo].[SP_LOAIMONAN_INSERT] 2, N'Món Vịt'
GO
[dbo].[SP_LOAIMONAN_INSERT] 3, N'Món Lợn'
GO
[dbo].[SP_LOAIMONAN_INSERT] 4, N'Món Cá'
GO
[dbo].[SP_LOAIMONAN_INSERT] 5, N'Bánh'
GO
[dbo].[SP_LOAIMONAN_INSERT] 6, N'Nước Ngọt'
GO
[dbo].[SP_LOAIMONAN_INSERT] 7, N'Đồ Uống Có Cồn'
GO
[dbo].[SP_LOAIMONAN_INSERT] 8, N'Món Tránh Miệng'
GO

-- BẢNG 3 -- Món ăn
CREATE PROCEDURE SP_MONAN_INSERT
	@MAMONAN INT,
	@TENGOI NVARCHAR(50),
	@DONVITINH NVARCHAR(20),
	@MALOAIMONAN INT,
	@DONGIA INT
AS
BEGIN
	INSERT INTO MONAN(MAMONAN, TENGOI, DONVITINH, MALOAIMONAN,DONGIA)
	VALUES(@MAMONAN, @TENGOI, @DONVITINH, @MALOAIMONAN, @DONGIA)
END
GO
-- Xóa dữ liệu cũ
DELETE MONAN 
GO
-- Thêm dữ liệu mới
[dbo].[SP_MONAN_INSERT] 1, N'Gà Xé Phay', N'Đĩa', 1, 150000
GO
[dbo].[SP_MONAN_INSERT] 2, N'Gà Quay', N'Đĩa', 1, 160000
GO
[dbo].[SP_MONAN_INSERT] 3, N'Gà Chiên Giòn', N'Đĩa', 1, 180000
GO
[dbo].[SP_MONAN_INSERT] 4, N'Vịt Quay', N'Đĩa', 2, 150000
GO
[dbo].[SP_MONAN_INSERT] 5, N'Vịt Nướng', N'Đĩa', 2, 150000
GO
[dbo].[SP_MONAN_INSERT] 6, N'Vịt Luộc', N'Đĩa', 2, 150000
GO
[dbo].[SP_MONAN_INSERT] 7, N'Thịt Lợn Rừng Nường', N'Đĩa', 3, 140000
GO
[dbo].[SP_MONAN_INSERT] 8, N'Lợn Quay', N'Đĩa', 3, 160000
GO
[dbo].[SP_MONAN_INSERT] 9, N'Lợn Nướng', N'Đĩa', 3, 190000
GO
[dbo].[SP_MONAN_INSERT] 10, N'Cá Hấp Bia', N'Đĩa', 4, 180000
GO
[dbo].[SP_MONAN_INSERT] 11, N'Cá Chiên Giòn', N'Đĩa', 4, 150000
GO
[dbo].[SP_MONAN_INSERT] 12, N'Cá Hấp', N'Đĩa', 4, 150000
GO

[dbo].[SP_MONAN_INSERT] 13, N'Bánh Ngọt', N'Chiếc', 5, 150000
GO
[dbo].[SP_MONAN_INSERT] 14, N'Bánh Sinh Nhật', N'Chiếc', 5, 160000
GO
[dbo].[SP_MONAN_INSERT] 15, N'Bánh Bao Nướng', N'Chiếc', 5, 150000
GO
[dbo].[SP_MONAN_INSERT] 16, N'CoCa CoLa', N'Lon', 6, 170000
GO
[dbo].[SP_MONAN_INSERT] 17, N'Pepsi', N'Lon', 6, 10000
GO
[dbo].[SP_MONAN_INSERT] 18, N'Fanta', N'Lon', 6, 10000
GO
[dbo].[SP_MONAN_INSERT] 19, N'Volka', N'Chai', 7, 1500000
GO
[dbo].[SP_MONAN_INSERT] 20, N'Rượu Trắng', N'Chai', 7, 160000
GO
[dbo].[SP_MONAN_INSERT] 21, N'Rượu Cần', N'Chai', 7, 160000
GO
[dbo].[SP_MONAN_INSERT] 22, N'Canh', N'Chén', 8, 160000
GO
[dbo].[SP_MONAN_INSERT] 23, N'Bánh Quy', N'Đĩa', 8, 150000
GO
[dbo].[SP_MONAN_INSERT] 24, N'Trà', N'Chén', 8, 100000
GO
[dbo].[SP_MONAN_INSERT] 25, N'Hoa Quả', N'Đĩa', 8, 150000
GO

-- BẢNG 4 -- Nhà sản xuất
CREATE PROCEDURE SP_NHASANXUAT_INSERT
	@MANHASANXUAT INT,
	@TENNHASANXUAT NVARCHAR(50),
	@DIADIEM NVARCHAR(50)
AS
BEGIN
	INSERT INTO NHASANXUAT(MANHASANXUAT, TENNHASANXUAT, DIADIEM)
	VALUES(@MANHASANXUAT, @TENNHASANXUAT, @DIADIEM)
END
GO
-- Delete dữ liệu cũ nhà sản xuất
DELETE NHASANXUAT
GO
-- Thêm dữ liệu
[dbo].[SP_NHASANXUAT_INSERT] 1, N'Cơ Sở Táo Sạch', N'Thái Bình'
GO
[dbo].[SP_NHASANXUAT_INSERT] 2, N'Cơ Sở Rau Tươi', N'Bắc Ninh'
GO
[dbo].[SP_NHASANXUAT_INSERT] 3, N'Trang Trại Vịt', N'Bắc Giang'
GO
[dbo].[SP_NHASANXUAT_INSERT] 4, N'Trang Trại Gà', N'Yên Bái'
GO
[dbo].[SP_NHASANXUAT_INSERT] 5, N'Ao Cá Sạch', N'Sơn La'
GO
[dbo].[SP_NHASANXUAT_INSERT] 6, N'Trang Trại Lợn', N'Hà Nội'
GO
[dbo].[SP_NHASANXUAT_INSERT] 7, N'Cơ Sở Chế Biến Đồ Đông Lanh', N'Hà Giang'
GO

-- BẢNG 5 -- Nguyên liệu
CREATE PROCEDURE SP_NGUYENLIEU_INSERT
	@MANGUYENLIEU INT,
	@TENNGUYENLIEU NVARCHAR(50),
	@DONVITINH NVARCHAR(20),
	@MANHASANXUAT INT
AS
BEGIN
	INSERT INTO NGUYENLIEU(MANGUYENLIEU, TENNGUYENLIEU, DONVITINH, MANHASANXUAT)
	VALUES (@MANGUYENLIEU, @TENNGUYENLIEU, @DONVITINH, @MANHASANXUAT)
END
GO
-- Xóa dự liệu cũ
DELETE NGUYENLIEU
GO
-- Thêm mới dữ liệu
[dbo].[SP_NGUYENLIEU_INSERT] 1, N'Gà Rừng', N'Kg', 4 
GO
[dbo].[SP_NGUYENLIEU_INSERT] 2, N'Gà Đông Cảo', N'Kg', 4 
GO
[dbo].[SP_NGUYENLIEU_INSERT] 3, N'Gà Vườn', N'Kg', 4 
GO
[dbo].[SP_NGUYENLIEU_INSERT] 4, N'Táo Mèo', N'Kg', 1
GO
[dbo].[SP_NGUYENLIEU_INSERT] 5, N'Táo Hữu Cơ', N'Kg', 1
GO
[dbo].[SP_NGUYENLIEU_INSERT] 6, N'Táo Tàu', N'Kg', 1
GO
[dbo].[SP_NGUYENLIEU_INSERT] 7, N'Rau Thơm', N'Kg', 2
GO
[dbo].[SP_NGUYENLIEU_INSERT] 8, N'Rau Tươi', N'Kg', 2
GO
[dbo].[SP_NGUYENLIEU_INSERT] 9, N'Rau Hữu Cơ', N'Kg', 2
GO
[dbo].[SP_NGUYENLIEU_INSERT] 10, N'Vịt Cỏ', N'Kg', 3 
GO
[dbo].[SP_NGUYENLIEU_INSERT] 11, N'Vịt', N'Kg', 3
GO
[dbo].[SP_NGUYENLIEU_INSERT] 12, N'Vịt Bầu', N'Kg', 3
GO
[dbo].[SP_NGUYENLIEU_INSERT] 13, N'Cá Trắm', N'Kg', 5
GO
[dbo].[SP_NGUYENLIEU_INSERT] 14, N'Cá Chim', N'Kg', 5
GO
[dbo].[SP_NGUYENLIEU_INSERT] 15, N'Cá Trê', N'Kg', 5
GO
[dbo].[SP_NGUYENLIEU_INSERT] 16, N'Thịt Hộp', N'Hộp', 6
GO
[dbo].[SP_NGUYENLIEU_INSERT] 17, N'Cá Hộp', N'Hộp', 6 
GO
[dbo].[SP_NGUYENLIEU_INSERT] 18, N'Thực Phẩm Đông Lạnh', N'Hộp', 6 
GO

-- BẢNG 6 -- Bộ phận
CREATE PROCEDURE SP_BOPHAN_INSERT
	@MABOPHAN INT,
	@TENBOPHAN NVARCHAR(50),
	@MAQUANLY INT
AS
BEGIN
	INSERT INTO BOPHAN(MABOPHAN, TEBOPHAN, MAQUANLY)
	VALUES(@MABOPHAN, @TENBOPHAN, @MAQUANLY)
END
GO
-- Xóa dữ liệu
DELETE BOPHAN
GO
-- Thêm dữ liệu mới
[dbo].[SP_BOPHAN_INSERT] 1, N'Chăm Sóc Khách Hàng', 1
GO
[dbo].[SP_BOPHAN_INSERT] 2, N'Lễ Tân', 2
GO
[dbo].[SP_BOPHAN_INSERT] 3, N'Nhập Xuất Kho', 3
GO
[dbo].[SP_BOPHAN_INSERT] 4, N'Kế Toán', 4
GO
[dbo].[SP_BOPHAN_INSERT] 5, N'Bồi Bàn', 5
GO

-- BẢNG 7 -- Nhân viên

CREATE PROCEDURE SP_NHANVIEN_INSERT
	@MANHANVIEN INT,
	@HOVATEN NVARCHAR(50),
	@NGAYSINH DATE,
	@DIACHI NVARCHAR(50),
	@SODIENTHOAI CHAR(15),
	@LUONG INT,
	@MABOPHAN INT,
	@GIOITINH NVARCHAR(6)
AS
BEGIN
	INSERT INTO NHANVIEN(MANHANVIEN, HOVATEN, NGAYSINH, DIACHI, SODIENTHOAI, LUONG, MABOPHAN, GIOITINH)
	VALUES (@MANHANVIEN, @HOVATEN, @NGAYSINH, @DIACHI, @SODIENTHOAI, @LUONG, @MABOPHAN, @GIOITINH)
END
GO
-- DELETE dữ liệu 
DELETE NHANVIEN
GO
-- Thêm mới
[dbo].[SP_NHANVIEN_INSERT] 1, N'Trương Thị Cầm', '11-01-1998', N'Hà Nội', '0123456789', 10000000, 1, N'Nữ'
GO
[dbo].[SP_NHANVIEN_INSERT] 2, N'Vũ Ngọc Quỳnh', '11-01-1998', N'Hải Phòng', '0123456789', 3000000, 2,N'Nữ'
GO
[dbo].[SP_NHANVIEN_INSERT] 3, N'Vũ Ngọc Huỳnh', '11-01-1998', N'Hồ Chí Minh', '0123456789', 5000000, 3,N'Nam'
GO
[dbo].[SP_NHANVIEN_INSERT] 4, N'Phạm Thị Hoài', '11-01-1990', N'Hà Giang', '0123456789', 10000000, 4,N'Nữ'
GO
[dbo].[SP_NHANVIEN_INSERT] 5, N'Mai Quốc Tuấn', '11-01-1998', N'Cần Thơ', '0123456789', 3000000, 5,N'Nam'
GO
[dbo].[SP_NHANVIEN_INSERT] 6, N'Phạm Phú Cường', '12-12-1998', N'Hà Nội', '0123456789', 3100000, 1,N'Nam'
GO
[dbo].[SP_NHANVIEN_INSERT] 7, N'Đinh Xuân Nhất', '11-11-1998', N'Hải Phòng', '0123456789', 5000000, 2,N'Nam'
GO
[dbo].[SP_NHANVIEN_INSERT] 8, N'Phạm Ngọc Vượng', '11-01-1998', N'Vĩnh Yên', '0123456789', 2000000, 3,N'Nam'
GO
[dbo].[SP_NHANVIEN_INSERT] 9, N'Nguyễn Thị Phượng', '11-11-1998', N'Hà Nội', '0123456789', 4000000, 4,N'Nữ'
GO
[dbo].[SP_NHANVIEN_INSERT] 10, N'Phạm Mai Ngọc', '11-01-1998', N'Hải Phòng', '0123456789', 3000000, 5,N'Nữ'
GO
[dbo].[SP_NHANVIEN_INSERT] 11, N'Vũ Ngọc Quỳnh', '11-01-1998', N'Hải Phòng', '0123456789', 3000000, 1,N'Nữ'
GO
[dbo].[SP_NHANVIEN_INSERT] 12, N'Vũ Thị Mai', '11-01-1999', N'Hải Phòng', '0123456789', 3000000, 2,N'Nữ'
GO
[dbo].[SP_NHANVIEN_INSERT] 13, N'Nguyễn Ngọc Mai', '11-01-1998', N'Hải Phòng', '0123456789', 5000000, 3,N'Nữ'
GO
[dbo].[SP_NHANVIEN_INSERT] 14, N'Vũ Thùy Chi', '12-01-1998', N'Hải Phòng', '0123456789', 3000000, 4,N'Nữ'
GO
[dbo].[SP_NHANVIEN_INSERT] 15, N'Nguyễn Thị Mai Anh', '11-01-1998', N'Hải Phòng', '0123456789', 3000000, 5,N'Nữ'
GO
-- BẢNG 8 -- Phiếu nhập
CREATE PROCEDURE SP_PHIEUNHAP_INSERT
	@MAPHIEUNHAP INT,
	@NGAYNHAP DATE,
	@MANHANVIEN INT,
	@THANHTIEN INT
AS
BEGIN
	INSERT INTO PHIEUNHAP(MAPHIEUNHAP, NGAYNHAP, MANHANVIEN, THANHTIEN)
	VALUES (@MAPHIEUNHAP, @NGAYNHAP, @MANHANVIEN, @THANHTIEN)
END
GO
--
DELETE PHIEUNHAP 
GO
--
[dbo].[SP_PHIEUNHAP_INSERT] 1, '12-11-2018', 3, 180000 
GO
[dbo].[SP_PHIEUNHAP_INSERT] 2, '10-11-2018', 3, 280000 
GO
[dbo].[SP_PHIEUNHAP_INSERT] 3, '9-11-2018', 3, 380000 
GO
[dbo].[SP_PHIEUNHAP_INSERT] 4, '12-11-2018', 8, 480000 
GO
[dbo].[SP_PHIEUNHAP_INSERT] 5, '02-11-2016', 8, 580000 
GO
[dbo].[SP_PHIEUNHAP_INSERT] 6, '11-01-2018', 8, 680000 
GO
[dbo].[SP_PHIEUNHAP_INSERT] 7, '11-15-2018', 13, 780000 
GO
[dbo].[SP_PHIEUNHAP_INSERT] 8, '1-15-2018', 13, 880000 
GO
[dbo].[SP_PHIEUNHAP_INSERT] 9, '2-15-2018', 13, 980000 
GO


-- BẢNG 9 -- Chi tiết phiếu nhập
CREATE PROCEDURE SP_CHITIETPHIEUNHAP_INSERT
	@MAPHIEUNHAP INT,
	@MANGUYENLIEU INT,
	@SOLUONG INT,
	@DONGIA INT 

AS
BEGIN
	INSERT INTO CHITIETPHIEUNHAP(MAPHIEUNHAP, MANGUYENLIEU, SOLUONG, DONGIA)
	VALUES(@MAPHIEUNHAP, @MANGUYENLIEU, @SOLUONG, @DONGIA)
END
GO
-- DELETE dữ liệu cũ
DELETE CHITIETPHIEUNHAP
GO
-- Thêm dữ liệu mới
[dbo].[SP_CHITIETPHIEUNHAP_INSERT] 1, 1, 15, 150000
GO
[dbo].[SP_CHITIETPHIEUNHAP_INSERT] 1, 2, 15, 140000
GO
[dbo].[SP_CHITIETPHIEUNHAP_INSERT] 1, 3, 15, 130000
GO
[dbo].[SP_CHITIETPHIEUNHAP_INSERT] 2, 1, 15, 120000
GO
[dbo].[SP_CHITIETPHIEUNHAP_INSERT] 2, 2, 15, 100000
GO
[dbo].[SP_CHITIETPHIEUNHAP_INSERT] 2, 3, 15, 156000
GO
[dbo].[SP_CHITIETPHIEUNHAP_INSERT] 3, 11, 15, 153000
GO
[dbo].[SP_CHITIETPHIEUNHAP_INSERT] 3, 12, 15, 1500000
GO
[dbo].[SP_CHITIETPHIEUNHAP_INSERT] 4, 14, 15, 120000
GO
[dbo].[SP_CHITIETPHIEUNHAP_INSERT] 4, 15, 15, 130000
GO
[dbo].[SP_CHITIETPHIEUNHAP_INSERT] 4, 6, 15, 160000
GO
[dbo].[SP_CHITIETPHIEUNHAP_INSERT] 5, 1, 15, 170000
GO
[dbo].[SP_CHITIETPHIEUNHAP_INSERT] 5, 2, 15, 180000
GO
[dbo].[SP_CHITIETPHIEUNHAP_INSERT] 5, 3, 15, 190000
GO
[dbo].[SP_CHITIETPHIEUNHAP_INSERT] 6, 1, 15, 200000
GO
[dbo].[SP_CHITIETPHIEUNHAP_INSERT] 6, 2, 15, 220000
GO
[dbo].[SP_CHITIETPHIEUNHAP_INSERT] 6, 3, 15, 230000
GO
[dbo].[SP_CHITIETPHIEUNHAP_INSERT] 7, 4, 15, 1250000
GO
[dbo].[SP_CHITIETPHIEUNHAP_INSERT] 7, 5, 15, 26000
GO
[dbo].[SP_CHITIETPHIEUNHAP_INSERT] 8, 6, 15, 130000
GO
[dbo].[SP_CHITIETPHIEUNHAP_INSERT] 8, 7, 15, 120000
GO
[dbo].[SP_CHITIETPHIEUNHAP_INSERT] 8, 8, 15, 150000
GO
[dbo].[SP_CHITIETPHIEUNHAP_INSERT] 9, 9, 15, 150000
GO
[dbo].[SP_CHITIETPHIEUNHAP_INSERT] 9, 10, 15, 150000
GO
-- BẢNG 10 -- Khách hàng
CREATE PROCEDURE SP_KHACHHANG_INSERT
	@MAKHACHHANG INT,
	@HOTEN NVARCHAR(50),
	@SODIENTHOAI CHAR(15),
	@DIACHI NVARCHAR(50)
AS
BEGIN
	INSERT INTO KHACHHANG(MAKHACHHANG, HOTEN, SODIENTHOAI, DIACHI)
	VALUES(@MAKHACHHANG, @HOTEN, @SODIENTHOAI, @DIACHI)
END
GO
[dbo].[SP_KHACHHANG_INSERT] 1, N'Nguyễn Minh Châu', '043218666', N'Hà Nội'
GO
[dbo].[SP_KHACHHANG_INSERT] 2, N'Nguyễn Ngọc Khánh', '043218111', N'Hải Phòng'
GO
[dbo].[SP_KHACHHANG_INSERT] 3, N'Nguyễn Minh Quân', '043218777', N'Hà Nam'
GO
[dbo].[SP_KHACHHANG_INSERT] 4, N'Nguyễn Ngọc Anh', '043218432', N'Hà Giang'
GO
[dbo].[SP_KHACHHANG_INSERT] 5, N'Nguyễn Hà Anh Quân', '043212222', N'Hồ Chí Minh'
GO
[dbo].[SP_KHACHHANG_INSERT] 6, N'Nguyễn Thị Hải Yến', '043218777', N'Đà Lạt'
GO
[dbo].[SP_KHACHHANG_INSERT] 7, N'Nguyễn Bảo Sơn', '043555777', N'Vinh'
GO
[dbo].[SP_KHACHHANG_INSERT] 8, N'Nguyễn Ngọc Thiện', '043219777', N'Hà Nam'
GO
[dbo].[SP_KHACHHANG_INSERT] 9, N'Mai Thị Trang', '042218777', N'Yên Bái'
GO
[dbo].[SP_KHACHHANG_INSERT] 10, N'Khổng Thị Vân', '042348777', N'Lạng Giang'
GO
[dbo].[SP_KHACHHANG_INSERT] 11, N'Đào Thị Vân', '043218997', N'Hà Nội'
GO
[dbo].[SP_KHACHHANG_INSERT] 12, N'Nguyễn Thị Ánh Tuyết', '043348777', N'Hà Nội'
GO
[dbo].[SP_KHACHHANG_INSERT] 13, N'Đinh Thị Thu', '043213377', N'Hà Nội'
GO
[dbo].[SP_KHACHHANG_INSERT] 14, N'Nguyễn Mai Trang', '013218777', N'Hà Nam'
GO
[dbo].[SP_KHACHHANG_INSERT] 15, N'Nguyễn Văn Vượng', '043212777', N'Hà Nam'
GO
[dbo].[SP_KHACHHANG_INSERT] 16, N'Nguyễn Ngọc Minh', '0432123777', N'Hà Nam'
GO
[dbo].[SP_KHACHHANG_INSERT] 17, N'Nguyễn Đức Hiệp', '0234418777', N'Hà Nam'
GO

-- BẢNG 11 -- Phiếu yêu cầu
CREATE PROCEDURE SP_PHIEUYEUCAU_INSERT
	@MAPHIEUYEUCAU INT,
	@TENPHIEU NVARCHAR(50),
	@NGAYVIETPHIEU DATE,
	@MAKHACHHANG INT
AS
BEGIN
	INSERT INTO PHIEUYEUCAU(MAPHIEUYEUCAU, TENPHIEU, NGAYVIETPHIEU, MAKHACHHANG)
	VALUES(@MAKHACHHANG, @TENPHIEU, @NGAYVIETPHIEU, @MAKHACHHANG)
END
GO
-- delete dữ liệu cũ
DELETE PHIEUYEUCAU
GO
-- thêm dữ liệu mới
[dbo].[SP_PHIEUYEUCAU_INSERT] 1, N'Đặt tiệc cưới', '11-02-2018', 1
GO
[dbo].[SP_PHIEUYEUCAU_INSERT] 2, N'Đặt bàn gia đình', '11-03-2018', 2
GO
[dbo].[SP_PHIEUYEUCAU_INSERT] 3, N'Đặt tiệc cưới', '11-04-2018', 3
GO
[dbo].[SP_PHIEUYEUCAU_INSERT] 4, N'Đặt tiệc mừng công', '11-05-2018', 4
GO
[dbo].[SP_PHIEUYEUCAU_INSERT] 5, N'Đặt tiệc sinh nhật', '11-06-2018', 5
GO
[dbo].[SP_PHIEUYEUCAU_INSERT] 6, N'Đặt bàn ăn', '11-07-2018', 6
GO
[dbo].[SP_PHIEUYEUCAU_INSERT] 7, N'Đặt tiệc cưới', '11-08-2018', 7
GO
[dbo].[SP_PHIEUYEUCAU_INSERT] 8, N'Đặt tiệc dạ hội', '11-09-2018', 8
GO
[dbo].[SP_PHIEUYEUCAU_INSERT] 9, N'Đặt tiệc sinh nhật', '11-10-2018', 9
GO
[dbo].[SP_PHIEUYEUCAU_INSERT] 10, N'Đặt tiệc chia tay', '11-11-2018', 10
GO
[dbo].[SP_PHIEUYEUCAU_INSERT] 11, N'Đặt tiệc cưới', '11-11-2018', 11
GO
[dbo].[SP_PHIEUYEUCAU_INSERT] 12, N'Đặt tiệc', '11-12-2018', 12
GO
[dbo].[SP_PHIEUYEUCAU_INSERT] 13, N'Đặt tiệc khánh công', '11-13-2018', 13
GO
[dbo].[SP_PHIEUYEUCAU_INSERT] 14, N'Đặt tiệc cưới', '11-14-2018', 14
GO
[dbo].[SP_PHIEUYEUCAU_INSERT] 15, N'Đặt bàn nhậu', '11-15-2018', 15
GO
[dbo].[SP_PHIEUYEUCAU_INSERT] 16, N'Đặt tiệc chia tay', '11-16-2018', 16
GO
[dbo].[SP_PHIEUYEUCAU_INSERT] 17, N'Đặt tiệc kỉ niệm sinh nhật công ty', '11-02-2018', 1
GO

-- BẢNG 12 -- Hóa đơn
CREATE PROCEDURE SP_HOADON_INSERT
	@MAHOADON INT,
	@NGAYLAPHOADON DATE,
	@THANHTIEN INT,
	@MAPHIEUYEUCAU INT,
	@MANHANVIEN INT
AS
BEGIN
	INSERT INTO HOADON(MAHOADON, NGAYLAPHOADON, THANHTIEN, MAPHIEUYEUCAU, MANHANVIEN)
	VALUES(@MAHOADON, @NGAYLAPHOADON, @THANHTIEN, @MAPHIEUYEUCAU, @MANHANVIEN)
END
GO
-- Delete dữ liệu cũ
DELETE HOADON
GO
-- Thêm dữ liệu mới 4, 9, 14
[dbo].[SP_HOADON_INSERT] 1, '11-01-2018', 1500000, 1, 4
GO
[dbo].[SP_HOADON_INSERT] 2, '11-02-2018', 1600000, 2, 4
GO
[dbo].[SP_HOADON_INSERT] 3, '11-03-2018', 1700000, 3, 4
GO
[dbo].[SP_HOADON_INSERT] 4, '11-04-2018', 1800000, 4, 9
GO
[dbo].[SP_HOADON_INSERT] 5, '11-05-2018', 1900000, 5, 9
GO
[dbo].[SP_HOADON_INSERT] 6, '11-06-2018', 2000000, 6, 9
GO
[dbo].[SP_HOADON_INSERT] 7, '11-07-2018', 2100000, 7, 14
GO
[dbo].[SP_HOADON_INSERT] 8, '11-08-2018', 500000, 8, 14
GO
[dbo].[SP_HOADON_INSERT] 9, '11-09-2018', 15000000, 9, 14
GO
[dbo].[SP_HOADON_INSERT] 10, '11-10-2018', 17000000,10, 4
GO
[dbo].[SP_HOADON_INSERT] 11, '11-11-2018', 28000000, 11, 4
GO
[dbo].[SP_HOADON_INSERT] 12, '11-12-2018', 35000000, 12, 4
GO
[dbo].[SP_HOADON_INSERT] 13, '11-13-2018', 37000000, 13, 4
GO
[dbo].[SP_HOADON_INSERT] 14, '11-14-2018', 20000000, 14, 4
GO
[dbo].[SP_HOADON_INSERT] 15, '11-15-2018', 1800000, 15, 4
GO
-- BẢNG 13 -- Chi tiết bàn ăn
CREATE PROCEDURE SP_CHITIETBANAN_INSERT
	@MABANAN INT,
	@MAHOADON INT
AS
	DECLARE @THOIGIANDAT DATE
BEGIN
	SELECT @THOIGIANDAT = HOADON.NGAYLAPHOADON FROM HOADON WHERE HOADON.MAHOADON = @MAHOADON

	INSERT INTO CHITIETBANAN(MABANAN, MAHOADON, THOIGIANDAT)
	VALUES (@MABANAN, @MAHOADON, @THOIGIANDAT)
END
GO
-- Delete dữ liệu cũ
DELETE CHITIETBANAN
GO
-- Thêm dữ liệu mới
[dbo].[SP_CHITIETBANAN_INSERT] 1, 1 
GO
[dbo].[SP_CHITIETBANAN_INSERT] 1, 2 
GO
[dbo].[SP_CHITIETBANAN_INSERT] 1, 3 
GO
[dbo].[SP_CHITIETBANAN_INSERT] 1, 4 
GO
[dbo].[SP_CHITIETBANAN_INSERT] 1, 5 
GO
[dbo].[SP_CHITIETBANAN_INSERT] 1, 6 
GO
[dbo].[SP_CHITIETBANAN_INSERT] 2, 1 
GO
[dbo].[SP_CHITIETBANAN_INSERT] 2, 2
GO
[dbo].[SP_CHITIETBANAN_INSERT] 2, 3 
GO
[dbo].[SP_CHITIETBANAN_INSERT] 2, 4 
GO
[dbo].[SP_CHITIETBANAN_INSERT] 2, 5 
GO
[dbo].[SP_CHITIETBANAN_INSERT] 2, 6 
GO
[dbo].[SP_CHITIETBANAN_INSERT] 3, 2
GO
[dbo].[SP_CHITIETBANAN_INSERT] 3, 3 
GO
[dbo].[SP_CHITIETBANAN_INSERT] 3, 4 
GO
[dbo].[SP_CHITIETBANAN_INSERT] 3, 5 
GO
[dbo].[SP_CHITIETBANAN_INSERT] 3, 5
GO
[dbo].[SP_CHITIETBANAN_INSERT] 4, 7 
GO
[dbo].[SP_CHITIETBANAN_INSERT] 5, 9 
GO
[dbo].[SP_CHITIETBANAN_INSERT] 6, 12 
GO
[dbo].[SP_CHITIETBANAN_INSERT] 7, 13
GO
[dbo].[SP_CHITIETBANAN_INSERT] 8, 15
GO
[dbo].[SP_CHITIETBANAN_INSERT] 9, 13
GO
[dbo].[SP_CHITIETBANAN_INSERT] 10, 12 
GO
[dbo].[SP_CHITIETBANAN_INSERT] 11, 11 
GO
[dbo].[SP_CHITIETBANAN_INSERT] 12, 10 
GO
[dbo].[SP_CHITIETBANAN_INSERT] 13, 11 
GO
[dbo].[SP_CHITIETBANAN_INSERT] 14, 12 
GO
[dbo].[SP_CHITIETBANAN_INSERT] 15, 12 
GO

-- BẢNG 14 -- Chi tiết phiếu yêu cầu
CREATE PROCEDURE SP_CHITIETPHIEUYEUCAU_INSERT
	@MAMONAN INT,
	@MAPHIEUYEUCAU INT,
	@SOLUONG INT
AS
	DECLARE @DONGIA INT,  @DONVITINH NVARCHAR(20)
BEGIN
	SELECT @DONGIA = DONGIA, @DONVITINH = DONVITINH FROM MONAN WHERE MAMONAN = @MAMONAN
	INSERT INTO CHITIETPHIEUYEUCAU(MAMONAN, MAPHIEUYEUCAU, DONGIA, DONVITINH, SOLUONG)
	VALUES(@MAMONAN, @MAPHIEUYEUCAU, @DONGIA, @DONVITINH, @SOLUONG)
END
GO
-- Delete dữ liệu
DELETE CHITIETPHIEUYEUCAU
GO
-- Thêm dữ liệu
[dbo].[SP_CHITIETPHIEUYEUCAU_INSERT] 1, 1, 10
GO
[dbo].[SP_CHITIETPHIEUYEUCAU_INSERT] 2, 1, 10
GO
[dbo].[SP_CHITIETPHIEUYEUCAU_INSERT] 3, 2, 10
GO
[dbo].[SP_CHITIETPHIEUYEUCAU_INSERT] 4, 3, 10
GO
[dbo].[SP_CHITIETPHIEUYEUCAU_INSERT] 5, 3, 10
GO
[dbo].[SP_CHITIETPHIEUYEUCAU_INSERT] 6, 2, 10
GO
[dbo].[SP_CHITIETPHIEUYEUCAU_INSERT] 7, 3, 10
GO
[dbo].[SP_CHITIETPHIEUYEUCAU_INSERT] 8, 1, 10
GO
[dbo].[SP_CHITIETPHIEUYEUCAU_INSERT] 9, 1, 10
GO
[dbo].[SP_CHITIETPHIEUYEUCAU_INSERT] 10, 2, 10
GO
[dbo].[SP_CHITIETPHIEUYEUCAU_INSERT] 11, 1, 10
GO
[dbo].[SP_CHITIETPHIEUYEUCAU_INSERT] 12, 1, 10
GO
[dbo].[SP_CHITIETPHIEUYEUCAU_INSERT] 13, 1, 10
GO
[dbo].[SP_CHITIETPHIEUYEUCAU_INSERT] 13, 5, 10
GO
[dbo].[SP_CHITIETPHIEUYEUCAU_INSERT] 10, 5, 10
GO
[dbo].[SP_CHITIETPHIEUYEUCAU_INSERT] 13, 6, 10
GO
[dbo].[SP_CHITIETPHIEUYEUCAU_INSERT] 1, 5, 10
GO
[dbo].[SP_CHITIETPHIEUYEUCAU_INSERT] 12, 6, 10
GO
[dbo].[SP_CHITIETPHIEUYEUCAU_INSERT] 14, 6, 10
GO

--------------------------------------------------------------------------------------------------------------------------
---------------------------30 CÂU TRUY VẤN DỮ LIỆU------------------------------------------------------------------------
-- 11.CHỌN - CHIẾU TRÊN 1 BẢNG : Lấy ra thông tin những khách hàng có địa chỉ tại Hà Nội hoặc Hải Phòng. Thông tin đưa ra gồm : Mã khách khàng, Họ tên khách hàng, Số điện thoại liên lạc
SELECT MAKHACHHANG, HOTEN, SODIENTHOAI, DIACHI
FROM KHACHHANG
WHERE DIACHI = N'Hà Nội' OR DIACHI = N'Hà Nam'

-- 12. TÍCH ĐECAC : Đưa ra mã khách hàng, tên khách hàng, mã hóa đơn, số tiền thanh toán của những khách hàng lập hóa đơn từ ngày ngày 01-11-2018 tới 10-11-2018
SELECT KH.MAKHACHHANG, KH.HOTEN, HD.MAHOADON, HD.THANHTIEN, HD.NGAYLAPHOADON
FROM KHACHHANG AS KH, HOADON AS HD, PHIEUYEUCAU AS PY
WHERE KH.MAKHACHHANG = PY.MAKHACHHANG AND HD.MAPHIEUYEUCAU = PY.MAPHIEUYEUCAU AND (HD.NGAYLAPHOADON BETWEEN '2018-11-01' AND '2018-11-10')

-- 13. Đưa ra các nhân viên ở Hải Phòng và ở bộ phận Lễ Tân có lương >= 2000000
SELECT NV.MANHANVIEN, NV.HOVATEN, NV.LUONG
FROM NHANVIEN AS NV, BOPHAN AS BP
WHERE NV.MABOPHAN = BP.MABOPHAN AND BP.TEBOPHAN = N'Lễ Tân' AND NV.LUONG >=200000

-- 14. Đưa ra nhân viên lập hóa đơn và cả những nhân viên chưa lập hóa đơn. Thông tin gồm mã nhân viên, họ và tên, ngày sinh, giới tính, mã hóa đơn
SELECT NV.MANHANVIEN, NV.HOVATEN, NV.GIOITINH, NV.NGAYSINH, HD.MAHOADON
FROM NHANVIEN AS NV LEFT JOIN HOADON AS HD ON NV.MANHANVIEN = HD.MANHANVIEN

-- 15. Thống kê số lượng hóa đơn do nhân viên nhập. Thông tin gồm mã nhân viên, họ tên, ngày sinh, giới tính, số lượng hóa đơn
SELECT NV.MANHANVIEN, NV.HOVATEN, NV.GIOITINH, NV.NGAYSINH, COUNT(HD.MAHOADON) SOLUONGHOADON
FROM NHANVIEN AS NV, HOADON AS HD
WHERE NV.MANHANVIEN = HD.MANHANVIEN
GROUP BY NV.MANHANVIEN, NV.HOVATEN, NV.GIOITINH, NV.NGAYSINH

-- 16. Đưa ra các bộ phận và tổng lương phải trả hàng tháng của từng phòng ban
SELECT BP.MABOPHAN, BP.TEBOPHAN, SUM(NV.LUONG) AS TONGLUONG
FROM BOPHAN AS BP, NHANVIEN AS NV
WHERE BP.MABOPHAN = NV.MABOPHAN
GROUP BY BP.MABOPHAN, BP.TEBOPHAN
-- 17. Đưa ra mã bàn ăn, số ghế của những hóa đơn có thành tiền > 5000000
SELECT BA.MABANAN, BA.SOGHE, HD.MAHOADON
FROM BANAN AS BA, CHITIETBANAN AS CT, HOADON AS HD
WHERE HD.MAHOADON = CT.MAHOADON AND CT.MABANAN = BA.MABANAN AND HD.THANHTIEN > 5000000
-- 18. Đưa ra mã bộ phận, tên bộ phận, tên của những nhân viên lập hóa đơn > 5000000
SELECT BP.MABOPHAN, BP.TEBOPHAN, NV.MANHANVIEN, NV.HOVATEN, NV.NGAYSINH, NV.GIOITINH
FROM BOPHAN AS BP, NHANVIEN AS NV, HOADON AS HD
WHERE BP.MABOPHAN = NV.MABOPHAN AND HD.MANHANVIEN = NV.MANHANVIEN AND HD.THANHTIEN > 5000000
-- 19. Đưa ra những khách hàng có hóa đơn trên 5000000
SELECT KH.MAKHACHHANG, KH.HOTEN, KH.DIACHI, HD.MAHOADON, HD.NGAYLAPHOADON, HD.THANHTIEN
FROM HOADON AS HD, PHIEUYEUCAU AS PY, KHACHHANG AS KH
WHERE HD.MAPHIEUYEUCAU = PY.MAPHIEUYEUCAU AND PY.MAKHACHHANG = KH.MAKHACHHANG AND HD.THANHTIEN >= 5000000

-- 20. Tính tổng tiền các phiếu nhập từ 1-1 tới 20-11 năm 2018
SELECT SUM(THANHTIEN) N'Tổng Số Tiền'
FROM PHIEUNHAP 
WHERE NGAYNHAP >= '2018-1-1' AND NGAYNHAP <= '2018-11-20'

-- 21. Đưa ra loại món ăn, tên của từng món ăn, đơn vị tính, đơn giá của từng món ăn
SELECT MA.MAMONAN, MA.TENGOI, MA.TENGOI, MA.DONVITINH, LM.TENGOI
FROM MONAN AS MA, LOAIMONAN AS LM
WHERE MA.MALOAIMONAN = LM.MALOAIMONAN
-- 22. Tăng lương cho những nhân viên dưới 5 triệu lên 5 triệu
UPDATE NHANVIEN
SET LUONG = 5000000
WHERE NHANVIEN.LUONG < 5000000
SELECT * FROM NHANVIEN
-- 23. Thêm nhân viên mới thuộc bộ phận kế toán
DECLARE @MANOPHAN INT
SELECT @MANOPHAN = MABOPHAN FROM BOPHAN WHERE TEBOPHAN = N'Kế Toán'
INSERT INTO NHANVIEN(MANHANVIEN, HOVATEN, NGAYSINH, DIACHI, SODIENTHOAI, LUONG, MABOPHAN)
VALUES(16, N'Nguyễn Văn Dần', '1992-11-11', N'Hà Nội', '123456789',10000000, @MANOPHAN)

-- 24. Tính tổng số lượng nhân viên, lương trung bình của từng bộ phận
SELECT BP.MABOPHAN,BP.TEBOPHAN, COUNT(NV.MANHANVIEN) AS N'Tổng số nhân viên', AVG(NV.LUONG) AS N'Lương trung bình'
FROM BOPHAN AS BP, NHANVIEN AS NV
WHERE BP.MABOPHAN = NV.MABOPHAN 
GROUP BY BP.MABOPHAN, BP.TEBOPHAN

-- 25. Đưa ra mã nhân viên, tên bộ phận, tên nhân viên, số lượng phiếu nhập của những nhân viên nhập phiếu
SELECT NV.MANHANVIEN, NV.HOVATEN, NV.NGAYSINH, NV.MABOPHAN, BP.TEBOPHAN, COUNT(PN.MAPHIEUNHAP) AS SOLUONGPHIEU
FROM NHANVIEN AS NV, PHIEUNHAP AS PN, BOPHAN AS BP
WHERE NV.MANHANVIEN = PN.MANHANVIEN AND BP.MABOPHAN = NV.MABOPHAN
GROUP BY NV.MANHANVIEN, NV.HOVATEN, NV.NGAYSINH, NV.MABOPHAN, BP.TEBOPHAN
-- 26. Đưa ra mức lương cao nhất của bộ phận 2
SELECT NV.MANHANVIEN, NV.HOVATEN, LUONG
FROM NHANVIEN AS NV 
WHERE NV.MABOPHAN = 2 AND NV.LUONG >= ALL(SELECT LUONG FROM NHANVIEN WHERE MABOPHAN = 2)


-- 27. Đưa ra hóa đơn có giá trị cao nhất
SELECT HD.MAHOADON, HD.THANHTIEN
FROM HOADON AS HD
WHERE HD.THANHTIEN >= ALL (SELECT THANHTIEN FROM HOADON)
-- 28. Đếm số lượng ghế và số lượng bàn ăn theo từng hóa đơn

SELECT HD.MAHOADON, COUNT(BA.MABANAN), SUM(BA.SOGHE)
FROM HOADON AS HD, BANAN AS BA, CHITIETBANAN AS CT
WHERE HD.MAHOADON = CT.MAHOADON AND CT.MABANAN = BA.MABANAN
GROUP BY HD.MAHOADON

-- 29. Đếm số lượng hóa đơn từng ngày từ ngày 01-11 tới 20-11-2018
SELECT COUNT(HD.NGAYLAPHOADON)
FROM HOADON AS HD
WHERE HD.NGAYLAPHOADON BETWEEN '2018-11-01' AND '2018-11-20'

-- 30. Đưa ra những món ăn mà khách hàng ở Hà Nội yêu cầu
SELECT MA.MAMONAN, MA.TENGOI, MA.DONGIA
FROM KHACHHANG AS KH, CHITIETPHIEUYEUCAU AS CT, MONAN AS MA, PHIEUYEUCAU AS PY
WHERE KH.MAKHACHHANG = PY.MAKHACHHANG AND PY.MAPHIEUYEUCAU = CT.MAPHIEUYEUCAU AND CT.MAMONAN = MA.MAMONAN
-- 1. Đưa ra mã khách hàng, tên khách hàng, mã phiếu yêu cầu, tên phiếu yêu cầu
SELECT KH.MAKHACHHANG, KH.HOTEN, PY.MAPHIEUYEUCAU, PY.TENPHIEU
FROM KHACHHANG AS KH, PHIEUYEUCAU AS PY
WHERE KH.MAKHACHHANG = PY.MAKHACHHANG
-- 2. Đưa ra mã nhân viên, họ và tên, ngày sinh, giới tính, bộ phận (nếu có)
SELECT NV.MANHANVIEN, NV.HOVATEN, NV.NGAYSINH, NV.GIOITINH, BP.TEBOPHAN
FROM NHANVIEN AS NV LEFT JOIN BOPHAN AS BP ON NV.MABOPHAN = BP.MABOPHAN

-- 3. Đưa ra mã nhà sản xuất, địa điểm, nguyên liệu, đơn vị tính và giá nguyên liệu > 500000
SELECT NS.MANHASANXUAT, NS.DIADIEM, NL.TENNGUYENLIEU, NL.DONVITINH, CT.DONGIA
FROM NHASANXUAT AS NS, NGUYENLIEU AS NL, CHITIETPHIEUNHAP AS CT
WHERE NS.MANHASANXUAT = NL.MANGUYENLIEU AND NL.MANGUYENLIEU = CT.MANGUYENLIEU AND CT.DONGIA > 10000

-- 4. Đưa ra mã nhân viên, họ và tên , mã hóa đơn, ngày nhập hóa đơn và cả những nhân viên chưa lập hóa đơn
SELECT NV.MANHANVIEN, NV.HOVATEN, HD.MAHOADON, HD.NGAYLAPHOADON
FROM NHANVIEN AS NV LEFT JOIN HOADON AS HD ON NV.MANHANVIEN = HD.MANHANVIEN

-- 5. Đưa ra mã nhân viên, họ tên, ngày sinh, mã bộ phận, tên bộ phận và có lương > 5000000, nhân viên chưa biên chế vào bộ phận và cả những bộ phận không có nhân viên
SELECT NV.MANHANVIEN, NV.HOVATEN, NV.NGAYSINH, NV.MABOPHAN, BP.MABOPHAN
FROM NHANVIEN AS NV FULL JOIN BOPHAN AS BP ON NV.MABOPHAN = BP.MABOPHAN

-- 6. Đưa ra mã khách hàng, tên khách hàng thanh toán hóa đơn > 5000000
SELECT KH.MAKHACHHANG, KH.HOTEN, HD.THANHTIEN
FROM KHACHHANG AS KH, PHIEUYEUCAU AS PY, HOADON AS HD
WHERE KH.MAKHACHHANG = PY.MAKHACHHANG AND HD.MAPHIEUYEUCAU = PY.MAPHIEUYEUCAU AND HD.THANHTIEN > 500000

-- 7. Đưa ra mã nhân viên, tên nhân viên, ngày sinh nhập phiếu nhập > 5000000
SELECT NV.MANHANVIEN, NV.HOVATEN, NV.NGAYSINH, PB.MAPHIEUNHAP, PB.NGAYNHAP
FROM NHANVIEN AS NV, PHIEUNHAP AS PB
WHERE NV.MANHANVIEN = PB.MANHANVIEN AND PB.THANHTIEN > 50000
-- 8. Đưa ra loại món ăn, mã món ăn , tên gọi món ăn có đơn giá > 10000
SELECT MA.MAMONAN, MA.DONGIA, MA.TENGOI, MA.MALOAIMONAN,LM.TENGOI, MA.DONGIA
FROM MONAN AS MA, LOAIMONAN AS LM
WHERE MA.MALOAIMONAN = LM.MALOAIMONAN AND MA.DONGIA > 10000
-- 9. Đưa ra mã nhân viên, tên nhân viên, ngày sinh của những nhân viên là quản lý
SELECT NV.MANHANVIEN, NV.HOVATEN, NV.NGAYSINH, NV.GIOITINH
FROM NHANVIEN AS NV
WHERE NV.MANHANVIEN IN (SELECT MAQUANLY FROM BOPHAN)

-- 10. Đưa ra những nhân viên chưa viết phiếu nhập
SELECT NV.MANHANVIEN, NV.HOVATEN, NV.NGAYSINH, NV.GIOITINH
FROM NHANVIEN AS NV 
WHERE NV.MANHANVIEN NOT IN (SELECT MANHANVIEN FROM PHIEUNHAP)
GO
------------------------LẬP TRÌNH TSQL------------------------
-- 1. Tạo thủ tục thêm một phiếu nhập
CREATE PROCEDURE SP_PHIEUNHAP_INSERT
	@MAPHIEUNHAP INT,
	@NGAYNHAP DATE,
	@MANHANVIEN INT,
	@THANHTIEN INT
AS
BEGIN
	INSERT INTO PHIEUNHAP(MAPHIEUNHAP, NGAYNHAP, MANHANVIEN, THANHTIEN)
	VALUES (@MAPHIEUNHAP, @NGAYNHAP, @MANHANVIEN, @THANHTIEN)
END
GO

-- 2. Tạo thủ tục thống kê số lượng hóa đơn đặt trong năm 2018. Thông tin gồm tổng số hóa đơn, tổng số giá trị tiền thanh toán
CREATE PROCEDURE SP_HOADON_THONGKE
AS
BEGIN
	SELECT COUNT(HD.MAHOADON) AS N'Tổng số hóa đơn', SUM(HD.THANHTIEN) AS N'Tổng số tiền'
	FROM HOADON AS HD
	WHERE HD.NGAYLAPHOADON >= '2018-01-01' AND HD.NGAYLAPHOADON <= '2018-12-31'
END
GO
-- 3. Tạo thủ tục thống kê số nhân viên của từng bộ phận. Thông tin đưa ra gồm: Mã bộ phận, tên bộ phận, tổng số nhân viên, tổng số lương phải trả cho nhân viên
CREATE PROCEDURE SP_NHANVIEN_THONGKE
AS
BEGIN
	SELECT BP.MABOPHAN, BP.TEBOPHAN, COUNT (DISTINCT NV.MANHANVIEN) AS N'Tổng số nhân viên', SUM(DISTINCT NV.LUONG) AS N'Tổng số lương'
	FROM NHANVIEN AS NV, BOPHAN AS BP
	WHERE NV.MABOPHAN = BP.MABOPHAN
	GROUP BY BP.MABOPHAN, BP.TEBOPHAN
	
END
GO
-- 4. Tạo thủ tục thống kê số lượng mặt hàng của từng nhà sản xuất có lượng mặt hàng > 2
CREATE PROCEDURE SP_NHASANXUAT_THONGKE
AS
BEGIN
	SELECT NSX.MANHASANXUAT, NSX.TENNHASANXUAT, COUNT( DISTINCT NL.MANGUYENLIEU)
	FROM NHASANXUAT AS NSX, NGUYENLIEU AS NL
	WHERE NSX.MANHASANXUAT = NL.MANHASANXUAT
	GROUP BY NSX.MANHASANXUAT, NSX.TENNHASANXUAT
	HAVING COUNT( DISTINCT NL.MANGUYENLIEU) > 2
END

GO
-- 5. Tạo thủ tục thống kê số lượng bàn ăn trên từng hóa đơn
CREATE PROCEDURE SP_BANAN_THONGKE
AS
BEGIN
	SELECT HD.MAHOADON, HD.NGAYLAPHOADON, COUNT(DISTINCT BA.MABANAN) AS N'Số lượng bàn ăn'
	FROM BANAN AS BA, CHITIETBANAN AS CT, HOADON AS HD
	WHERE BA.MABANAN = CT.MABANAN AND HD.MAHOADON = CT.MAHOADON
	GROUP BY HD.MAHOADON, HD.NGAYLAPHOADON
END
GO

-- 6. Thống kê các món ăn được đặt nhiều nhất tại nhà hàng
-- CÁCH 1 --
SELECT TOP 1 SUM(DISTINCT CT.SOLUONG) AS TONGSOLUONG
FROM MONAN AS MA, CHITIETPHIEUYEUCAU AS CT 
WHERE MA.MAMONAN = CT.MAMONAN
GROUP BY MA.MAMONAN
ORDER BY TONGSOLUONG DESC
GO

CREATE PROCEDURE SP_MONANNHIEUNHAT_THONGKE
AS
BEGIN
	SELECT MA.MAMONAN, MA.TENGOI, SUM(DISTINCT CT.SOLUONG)
	FROM MONAN AS MA, CHITIETPHIEUYEUCAU AS CT
	WHERE MA.MAMONAN = CT.MAMONAN
	GROUP BY MA.MAMONAN,  MA.TENGOI
	HAVING SUM(DISTINCT CT.SOLUONG) = (SELECT TOP 1 SUM(DISTINCT CT.SOLUONG) AS TONGSOLUONG
										FROM MONAN AS MA, CHITIETPHIEUYEUCAU AS CT 
										WHERE MA.MAMONAN = CT.MAMONAN
										GROUP BY MA.MAMONAN
										ORDER BY TONGSOLUONG DESC)
	 
					
END
GO
-- 7. Tạo function xem danh sách món ăn của nhà hàng THEO LOẠI MÓN ĂN
CREATE FUNCTION FUNC_DANHSACHMONAN (@MALOAIMONAN INT)
	RETURNS TABLE
AS
RETURN (
	SELECT MA.MAMONAN, MA.TENGOI, MA.DONVITINH, MA.DONGIA
	FROM LOAIMONAN AS LM, MONAN AS MA
	WHERE MA.MALOAIMONAN = LM.MALOAIMONAN AND LM.MALOAIMONAN = @MALOAIMONAN
)

SELECT * FROM FUNC_DANHSACHMONAN(2)
GO
-- 8. Tạo function thống kê các đơn hàng nhập từ các nhà sản xuất ở khu vực Hà nội. Thông tin gồm nhà sản xuất, tổng số lượng đơn hàng
CREATE FUNCTION  FUNC_NHASANXUAT (@DIAIDEM NVARCHAR(50))
	RETURNS TABLE
AS
RETURN (
	SELECT NSX.MANHASANXUAT, NSX.TENNHASANXUAT, COUNT (PN.MAPHIEUNHAP) AS TONGSOPHIEU
	FROM NHASANXUAT AS NSX, NGUYENLIEU AS NL, PHIEUNHAP AS PN, CHITIETPHIEUNHAP AS CT
	WHERE NSX.MANHASANXUAT = NL.MANHASANXUAT AND NL.MANGUYENLIEU = CT.MANGUYENLIEU AND CT.MAPHIEUNHAP = PN.MAPHIEUNHAP AND NSX.DIADIEM = @DIAIDEM
	GROUP BY NSX.MANHASANXUAT, NSX.TENNHASANXUAT
)

-- 9. Tạo trigger xóa 1 nhân viên
CREATE TRIGGER TRIG_XOANHANVIEN ON NHANVIEN INSTEAD OF
DELETE
AS
	DECLARE @MANHANVIEN INT
BEGIN
	SELECT @MANHANVIEN FROM deleted

	UPDATE HOADON  
	SET MANHANVIEN = NULL
	WHERE MANHANVIEN = @MANHANVIEN

	UPDATE PHIEUNHAP
	SET MANHANVIEN = NULL
	WHERE MAPHIEUNHAP = @MANHANVIEN

	DELETE NHANVIEN WHERE MANHANVIEN = @MANHANVIEN
	PRINT N'Xóa thành công'
	
END
GO

-- 10. Tạo 1 trigger khi thêm sửa một nhà sản xuất
CREATE TRIGGER TRIG_NHASANXUAT_XOA ON NHASANXUAT
FOR INSERT, UPDATE
AS
	
BEGIN
	DECLARE @MA INT, @TEN NVARCHAR(50), @DIADIEM NVARCHAR(50)
	SELECT @MA = MANHASANXUAT, @TEN = TENNHASANXUAT FROM deleted
	PRINT N'CẬP NHẬT ' + @TEN
	SELECT @MA = MANHASANXUAT, @TEN = TENNHASANXUAT FROM inserted 
	PRINT N'THÀNH ' + @TEN 
END 
GO

DELETE NHASANXUAT WHERE MANHASANXUAT = 8

INSERT INTO NHASANXUAT(MANHASANXUAT, TENNHASANXUAT, DIADIEM)
VALUES(8, N'Cơ sở tôm tươi', N'Hải Phòng')

UPDATE NHASANXUAT
SET TENNHASANXUAT = N'Tôm hùm'
WHERE MANHASANXUAT = 8

